NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="WStellar"
ORG_DBA="World Stellar Network"
ORG_URL="https://wstellar.github.io"
ORG_OFFICIAL_EMAIL="smart.crypto@atomicmail.io"
ORG_LOGO="https://wstellar.github.io/images/wstellar.png"
ORG_DESCRIPTION="Verified institution backing tokens on Stellar blockchain"

[[CURRENCIES]]
code="EGG"
issuer="GCBRHKK6HLMN2DKDQNFHFD3BBQEUUBR23T56TSYRNXCAVHTZRZ3TIEGG"
image="https://wstellar.github.io/images/EGG.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="EOS"
issuer="GAJYREW2F3LWOHD4VSBZGVRK46RE2YOFGGINDLIUOHIUJCUA2B7DZEOS"
image="https://wstellar.github.io/images/EOS.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="JPM"
issuer="GBZ6SQZ6AM6UWCQIV72JXRCKEKMJ6ZWZGB42XDNGDL3W7OLMDNZKHJPM"
image="https://wstellar.github.io/images/JPM.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="LTC"
issuer="GBA3TW4KGC4JKCQ3F7U4WDVRKHKQLBKS45CKM6HHRZNXJ6DMIBLCILTC"
image="https://wstellar.github.io/images/LTC.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="LUX"
issuer="GCKKE5XQTAIZF7BW2BOMOPUU45JUKADOY3FBV5HKZ2ZBLU3RFVWBBLUX"
image="https://wstellar.github.io/images/LUX.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="NFT"
issuer="GAXL6ZFO6MJCAAZMPJ7HYXRFKGSISUKCZMYXQVATWLZRNUZCDVS4ENFT"
image="https://wstellar.github.io/images/NFT.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="RDX"
issuer="GCOSQ6PGZPOUYJ2WMAN54SZZRSZRCOWPUAWJZQIQIT2EUXOLM5GWZRDX"
image="https://wstellar.github.io/images/RDX.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="ROK"
issuer="GD5EZNO6HQ6UDWHODEH2OZKDIH5SVFLLARPOLASUDIWAEOILDA7IKROK"
image="https://wstellar.github.io/images/ROK.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="RON"
issuer="GA6GICGBD2BPNAMN3AYCLVZH3ZT2VHPRJ65BUT7VRTR7ROSF3PBDIRON"
image="https://wstellar.github.io/images/RON.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="SSD"
issuer="GCJGGJLFBDFV4CTLJVVBKRIVAO5U4E74MFMYR5BZPHJS6PV77WHFUSSD"
image="https://wstellar.github.io/images/SSD.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="STX"
issuer="GDBZBASQHCTPZGGP7CZC4SKWSTO3DKO7G65AQNY2L2V2LCMFLAXUTSTX"
image="https://wstellar.github.io/images/STX.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="WWW"
issuer="GCH24YC2EAGSANNFHMMST6QC5DHXEE3KJGE7SRWI7UBLZGPS64KRAWWW"
image="https://wstellar.github.io/images/WWW.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="XDC"
issuer="GBUABXEZ3IVSSBCWL4QWIGODVQIHAD6PJLHBDCBLXQPDTCMCDQPZJXDC"
image="https://wstellar.github.io/images/XDC.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="XEM"
issuer="GDBRBGZYTSA6IAAVQWUD7XO4EDVPT3AGQFNQVHXBSQMB2RZQPQ7NNXEM"
image="https://wstellar.github.io/images/XEM.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="XLM"
issuer="GCMHQ4SZIH2TMB3DXQLUKKVFXJGO22346ZZDUEYXOL3DRFJ6I2JOFXLM"
image="https://wstellar.github.io/images/XLM.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="XLN"
issuer="GCZMLGHUIYRONCFDMUXKFQZYJCD3DDUFURFPLDJ7EHRLEFR2QMRDLXLN"
image="https://wstellar.github.io/images/XLN.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="XMP"
issuer="GCXAZMYQWJI3E65KHA6WLQMTWI5SKPRRYNXJM7A47OTNAXRABKP5LXMP"
image="https://wstellar.github.io/images/XMP.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000

[[CURRENCIES]]
code="ZEN"
issuer="GDKRYHYV6COZPMUKB3J7R5H6TXGYOAAF67YJOQZ3MJTMWICZ4SD2MZEN"
image="https://wstellar.github.io/images/ZEN.png"
conditions="financial and business"
display_decimals=7
fixed_number=100000000000
