NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="WStellar"
ORG_DBA="World Stellar Network"
ORG_URL="https://wstellar.github.io"
ORG_OFFICIAL_EMAIL="smart.crypto@atomicmail.io"
ORG_LOGO="https://wstellar.github.io/images/wstellar.png"
ORG_DESCRIPTION="Verified institution backing tokens on Stellar blockchain"
